"""Prompts for CLI operations"""

from .analysis import (
    CODE_ANALYSIS_PROMPT,
    SECURITY_ANALYSIS_PROMPT,
    PERFORMANCE_ANALYSIS_PROMPT,
)
from .refactoring import (
    REFACTOR_ANALYSIS_PROMPT,
    REFACTOR_SUGGESTION_PROMPT,
)

__all__ = [
    "CODE_ANALYSIS_PROMPT",
    "SECURITY_ANALYSIS_PROMPT",
    "PERFORMANCE_ANALYSIS_PROMPT",
    "REFACTOR_ANALYSIS_PROMPT",
    "REFACTOR_SUGGESTION_PROMPT",
]
